trigger:
  branches:
    include:
      - main

pool:
  name: BNDZ  

variables:
  dockerRegistryServiceConnection: 'bndzConnect'
  kubernetesServiceConnection: 'AzureKubernetesServiceSC'
  containerRegistry: 'bndzacr.azurecr.io'
  frontendImageName: 'frontend'
  backendImageName: 'backend'
  imageTag: '$(Build.BuildId)'
  imageUri: $(containerRegistry)/$(backendImageName):$(imageTag)

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Images
  jobs:
  - job: BuildPushJob
    displayName: Build and Push Frontend and Backend
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    # Build Frontend Docker Image
    - task: Docker@2
      displayName: Build frontend Docker image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(frontendImageName)
        command: build
        Dockerfile: src/frontend/Dockerfile
        tags: |
          $(imageTag)
        buildContext: src/frontend

    # Push Frontend Docker Image
    - task: Docker@2
      displayName: Push frontend Docker image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(frontendImageName)
        command: push
        tags: |
          $(imageTag)

    # Build Backend Docker Image
    - task: Docker@2
      displayName: Build backend Docker image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(backendImageName)
        command: build
        Dockerfile: src/backend/Dockerfile
        tags: |
          $(imageTag)
        buildContext: src/backend

    # Push Backend Docker Image
    - task: Docker@2
      displayName: Push backend Docker image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(backendImageName)
        command: push
        tags: |
          $(imageTag)

    - task: Bash@3
      displayName: Update backend.yaml image tag
      inputs:
        targetType: 'inline'
        script: |
          sed -i "s|image:.*|image: $(imageUri)|g" Manifest-Azure/backend.yaml

    - publish: Manifest-Azure/backend.yaml
      artifact: manifest


- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - job: DeployJob
    displayName: Deploy Kubernetes Manifests
    steps:

    - checkout: self

    - task: Kubernetes@1
      displayName: Deploy MongoDB
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)
        namespace: $(namespace)
        command: apply
        useConfigurationFile: true
        configuration: Manifest-Azure/mongodb.yaml

    - task: Kubernetes@1
      displayName: Deploy Backend
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)
        namespace: $(namespace)
        command: apply
        useConfigurationFile: true
        configuration: Manifest-Azure/backend.yaml

    - task: Kubernetes@1
      displayName: Deploy Frontend
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)
        namespace: $(namespace)
        command: apply
        useConfigurationFile: true
        configuration: Manifest-Azure/frontend.yaml